# Shared rsync settings for Ivy_Net ↔ UVA HPC (sourced by rsync_* wrappers).
#
# Callers must set:
#   IVY_NET_SCRIPTS_DIR   Absolute path to this scripts/ directory (dirname of the wrapper).
#
# Optional env overrides: HPC_USER, HPC_HOST, HPC_REPO, DRY_RUN=1
#
# Default targets (for the "all" shortcut):
#   tenure/tenure_pipeline   — code + all generated data outputs (with excludes below)
#   python_packages/dblp-parser  — XML dump + DTD (multi-GB; only sync when needed)
#
# Exclude logic (applied to EVERY push and pull):
#   faculty_snapshots/    — HTML archive; 10s of GB; lives on HPC only; never Mac→HPC
#   dblp_parsed/          — 433MB of JSONL; regenerable from XML; HPC-side only
#   _ipeds_cache/         — hundreds of MB of downloaded NCES zips; regenerable
#   _ipeds_probe/         — probe zips; regenerable
#   __pycache__/          — generated bytecode
#   *.pyc                 — compiled Python
#
# PUSH  (Mac → HPC): pushes code (*.py, notebooks, scripts, small CSVs).
#   Additional PUSH excludes keep large HPC-generated data files from flowing back:
#     faculty_panel*.jsonl, faculty_snapshots_*.jsonl, openalex_*.jsonl, openalex_*.json
#   (These are generated on HPC; no point overwriting them from Mac.)
#
# PULL  (HPC → Mac): pulls everything NOT excluded — so it brings back:
#     faculty_panel_enriched.jsonl, faculty_panel_with_pools.jsonl,
#     openalex_*.jsonl, PNGs, CSVs, any new *.py modules.
#   It still excludes faculty_snapshots/ and dblp_parsed/ (too big for Mac).

: "${IVY_NET_SCRIPTS_DIR:?IVY_NET_SCRIPTS_DIR must be set before sourcing rsync_hpc_include.sh}"

set -euo pipefail

REPO_ROOT="$(cd "${IVY_NET_SCRIPTS_DIR}/.." && pwd)"

HPC_USER="${HPC_USER:-dzk3ja}"
HPC_HOST="${HPC_HOST:-login.hpc.virginia.edu}"
HPC_REPO="${HPC_REPO:-~/Ivy_Net}"

REMOTE="${HPC_USER}@${HPC_HOST}"

# Default relative paths (under repo root) for "all" shortcut.
IVY_RSYNC_DEFAULT_TARGETS=(
  "tenure/tenure_pipeline"
  "python_packages/dblp-parser"
)

# Excludes applied to EVERY rsync (push + pull).
_IVY_RSYNC_COMMON_EXCLUDES=(
  "--exclude=faculty_snapshots/"       # HTML archive — HPC-only; grows to 10s of GB
  "--exclude=dblp_parsed/"             # 433MB JSONL — regenerable from XML
  "--exclude=_ipeds_cache/"            # NCES zip cache — regenerable
  "--exclude=_ipeds_probe/"            # probe zips — regenerable
  "--exclude=__pycache__/"             # generated bytecode
  "--exclude=*.pyc"
  "--exclude=*.pyo"
  "--exclude=.ipynb_checkpoints/"
  "--exclude=.DS_Store"
)

# Extra excludes for PUSH (Mac → HPC): don't overwrite HPC-generated large data
# from a Mac that may have stale or missing copies of those files.
_IVY_RSYNC_PUSH_EXCLUDES=(
  "--exclude=faculty_panel.jsonl"
  "--exclude=faculty_panel_collisions.jsonl"
  "--exclude=faculty_panel_enriched.jsonl"
  "--exclude=faculty_panel_with_pools.jsonl"
  "--exclude=faculty_panel_analysis*.jsonl"
  "--exclude=faculty_snapshots_plan.jsonl"
  "--exclude=faculty_snapshots_strategy_audit.jsonl"
  "--exclude=faculty_snapshots_index.jsonl"
  "--exclude=faculty_snapshots_parsed.jsonl"
  "--exclude=openalex_author_ids.jsonl"
  "--exclude=openalex_works_by_year.jsonl"
  "--exclude=openalex_snapshot_cache.jsonl"   # HPC-generated cache — never push from Mac
  "--exclude=openalex_low_confidence.jsonl"
  "--exclude=openalex_inst_map.json"
  "--exclude=faculty_url_suggestions.jsonl"   # HPC-generated by discover_faculty_urls.slurm
  "--exclude=faculty_url_suggestions.csv"     # same — pull only, never push
)

_ivy_rsync_build_opts() {
  RSYNC_OPTS=(-avz --progress)
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    RSYNC_OPTS+=(-n)
    echo "==> DRY RUN (no files changed)"
  fi
}

# Usage: ivy_rsync_push <relative-path>   e.g. tenure/tenure_pipeline
#   Pushes code and small tracked files; skips HPC-generated large data outputs.
ivy_rsync_push() {
  local rel="${1:?relative path required}"
  _ivy_rsync_build_opts
  local src="${REPO_ROOT}/${rel}/"
  local dst="${REMOTE}:${HPC_REPO}/${rel}/"
  echo "==> Push (code + small files) ${rel}"
  echo "    from: ${src}"
  echo "    to:   ${dst}"
  rsync "${RSYNC_OPTS[@]}" \
    "${_IVY_RSYNC_COMMON_EXCLUDES[@]}" \
    "${_IVY_RSYNC_PUSH_EXCLUDES[@]}" \
    "${src}" "${dst}"
  echo "==> Done."
}

# Usage: ivy_rsync_pull <relative-path>
#   Pulls all generated outputs from HPC (enriched panels, OA files, PNGs, CSVs).
#   Skips faculty_snapshots/ and dblp_parsed/ (too large for Mac).
ivy_rsync_pull() {
  local rel="${1:?relative path required}"
  _ivy_rsync_build_opts
  local src="${REMOTE}:${HPC_REPO}/${rel}/"
  local dst="${REPO_ROOT}/${rel}/"
  echo "==> Pull (all outputs except HTML + dblp) ${rel}"
  echo "    from: ${src}"
  echo "    to:   ${dst}"
  mkdir -p "${dst}"
  rsync "${RSYNC_OPTS[@]}" \
    "${_IVY_RSYNC_COMMON_EXCLUDES[@]}" \
    "${src}" "${dst}"
  echo "==> Done."
}
