# Shared rsync settings for Ivy_Net ↔ UVA HPC (sourced by rsync_* wrappers).
#
# Human-readable policy + workflows: scripts/DATA_SYNC.md
#
# Callers must set:
#   IVY_NET_SCRIPTS_DIR   Absolute path to this scripts/ directory (dirname of the wrapper).
#
# Optional env overrides: HPC_USER, HPC_HOST, HPC_REPO, DRY_RUN=1
#
# Default targets (for the "all" shortcut):
#   tenure/tenure_pipeline   — code + all generated data outputs (with excludes below)
# Do not include DBLP XML dumps in "all"; sync those manually and intentionally.
# Sweep shortcut:
#   sports/outputs/simulation_sweeps — 537 sweep code up, result files back
#
# Exclude logic (applied to EVERY push and pull):
#   faculty_snapshots/    — HTML archive; 10s of GB; lives on HPC only; never Mac→HPC
#   dblp_parsed/          — 433MB of JSONL; regenerable from XML; HPC-side only
#   _ipeds_cache/         — hundreds of MB of downloaded NCES zips; regenerable
#   _ipeds_probe/         — probe zips; regenerable
#   __pycache__/          — generated bytecode
#   *.pyc                 — compiled Python
#
# PUSH  (Mac → HPC): pushes code (*.py, notebooks, scripts, small CSVs).
#   Additional PUSH excludes keep large HPC-generated data files from flowing back:
#     faculty_panel*.jsonl, faculty_snapshots_*.jsonl, openalex_*.jsonl, openalex_*.json
#   (These are generated on HPC; no point overwriting them from Mac.)
#
# PULL  (HPC → Mac): pulls everything NOT excluded — so it brings back:
#     faculty_panel_enriched.jsonl, faculty_panel_with_pools.jsonl,
#     openalex_*.jsonl, PNGs, CSVs, any new *.py modules.
#   It still excludes faculty_snapshots/ and dblp_parsed/ (too big for Mac).

: "${IVY_NET_SCRIPTS_DIR:?IVY_NET_SCRIPTS_DIR must be set before sourcing rsync_hpc_include.sh}"

set -euo pipefail

REPO_ROOT="$(cd "${IVY_NET_SCRIPTS_DIR}/.." && pwd)"

HPC_USER="${HPC_USER:-dzk3ja}"
HPC_HOST="${HPC_HOST:-login.hpc.virginia.edu}"
HPC_REPO="${HPC_REPO:-~/Ivy_Net}"

REMOTE="${HPC_USER}@${HPC_HOST}"

# Default relative paths (under repo root) for "all" shortcut.
IVY_RSYNC_DEFAULT_TARGETS=(
  "tenure/tenure_pipeline"
)

# Narrow shortcut for faithful 537 / 538 sweeps (code push; results pull).
IVY_RSYNC_SWEEP_TARGET="sports/outputs/simulation_sweeps"

# Gitignored Big Fish unzipped panels + bulk MBB (rsync only — see pull_big_data.sh).
IVY_BIG_FISH_CSV_REL=(
  "datasets/football/football_big_fish_player_season_panel/football_big_fish_player_season_panel.csv"
  "datasets/legends/lol_big_fish_player_split_panel.csv"
)
IVY_BIG_FISH_ZIP_REL=(
  "datasets/football/football_big_fish_player_season_panel.csv.zip"
  "datasets/legends/lol_big_fish_player_split_panel.csv.zip"
)
IVY_RSYNC_MBB_TARGET="datasets/mbb"

# Shared rsync --include rules for datasets/ (used by pull_big_data push/pull).
_IVY_RSYNC_INC_BIG_FISH=(
  "--include=football/"
  "--include=football/football_big_fish_player_season_panel/"
  "--include=football/football_big_fish_player_season_panel/football_big_fish_player_season_panel.csv"
  "--include=legends/"
  "--include=legends/lol_big_fish_player_split_panel.csv"
)
_IVY_RSYNC_INC_EDUCATION=(
  "--include=nels88/"
  "--include=nels88/***"
  "--include=hsb80/"
  "--include=hsb80/***"
)
_IVY_RSYNC_INC_APACHE=(
  "--include=Apache/"
  "--include=Apache/***"
)
_IVY_RSYNC_INC_MBB=(
  "--include=mbb/"
  "--include=mbb/***"
)

IVY_RSYNC_TENURE_TARGET="tenure/tenure_pipeline"

_ivy_rsync_datasets_scoped() {
  local direction="${1:?push|pull}" scope="${2:?}"
  if [[ "${scope}" == "mbb" ]]; then
    if [[ "${direction}" == "push" ]]; then ivy_rsync_push_mbb; else ivy_rsync_pull_mbb; fi
    return
  fi
  if [[ "${direction}" == "push" && ( "${scope}" == "datasets" || "${scope}" == "big-fish" || "${scope}" == "big_fish" ) ]]; then
    ivy_unzip_big_fish
  fi
  _ivy_rsync_build_opts
  local includes=()
  case "${scope}" in
    datasets)
      includes+=("${_IVY_RSYNC_INC_BIG_FISH[@]}" "${_IVY_RSYNC_INC_EDUCATION[@]}" "${_IVY_RSYNC_INC_APACHE[@]}" "${_IVY_RSYNC_INC_MBB[@]}")
      ;;
    big-fish|big_fish)
      includes+=("${_IVY_RSYNC_INC_BIG_FISH[@]}")
      ;;
    education)
      includes+=("${_IVY_RSYNC_INC_EDUCATION[@]}")
      ;;
    apache)
      includes+=("${_IVY_RSYNC_INC_APACHE[@]}")
      ;;
    *)
      echo "Unknown datasets scope: ${scope}" >&2
      exit 1
      ;;
  esac
  includes+=("--exclude=*")
  local src dst
  if [[ "${direction}" == "push" ]]; then
    src="${REPO_ROOT}/datasets/"
    dst="${REMOTE}:${HPC_REPO}/datasets/"
    echo "==> Push datasets/ (${scope}: Mac → HPC)"
  else
    src="${REMOTE}:${HPC_REPO}/datasets/"
    dst="${REPO_ROOT}/datasets/"
    mkdir -p "${dst}"
    echo "==> Pull datasets/ (${scope}: HPC → Mac)"
  fi
  echo "    from: ${src}"
  echo "    to:   ${dst}"
  rsync "${RSYNC_OPTS[@]}" \
    "${_IVY_RSYNC_COMMON_EXCLUDES[@]}" \
    "${includes[@]}" \
    "${src}" "${dst}"
  echo "==> Done."
}

# Top-level sync: direction push|pull, scope all|datasets|big-fish|education|apache|mbb|tenure|sweep
ivy_rsync_sync_big_data() {
  local direction="${1:?push|pull}"
  local scope="${2:-all}"
  case "${scope}" in
    all)
      echo "==> BIG DATA (${scope}): datasets + tenure + sweep"
      _ivy_rsync_datasets_scoped "${direction}" datasets
      if [[ "${direction}" == "push" ]]; then
        ivy_rsync_push "${IVY_RSYNC_TENURE_TARGET}"
        echo "==> Note: sweep results are usually HPC → Mac only; skipping sweep on to-hpc all."
      else
        ivy_rsync_pull "${IVY_RSYNC_TENURE_TARGET}"
        ivy_rsync_pull_sweep
      fi
      ;;
    datasets|big-fish|big_fish|education|apache|mbb)
      _ivy_rsync_datasets_scoped "${direction}" "${scope}"
      ;;
    tenure)
      if [[ "${direction}" == "push" ]]; then
        ivy_rsync_push "${IVY_RSYNC_TENURE_TARGET}"
      else
        ivy_rsync_pull "${IVY_RSYNC_TENURE_TARGET}"
      fi
      ;;
    sweep)
      if [[ "${direction}" == "push" ]]; then
        echo "WARN: sweep results are normally pulled from HPC, not pushed. Use rsync_push_to_hpc.sh sweep for code." >&2
        ivy_rsync_push "${IVY_RSYNC_SWEEP_TARGET}"
      else
        ivy_rsync_pull_sweep
      fi
      ;;
    *)
      echo "Unknown scope: ${scope}" >&2
      echo "Scopes: all datasets big-fish education apache mbb tenure sweep" >&2
      echo "Catalog: scripts/BIG_DATA_MANIFEST.md" >&2
      exit 1
      ;;
  esac
}

# Excludes applied to EVERY rsync (push + pull).
_IVY_RSYNC_COMMON_EXCLUDES=(
  "--exclude=faculty_snapshots/"       # HTML archive — HPC-only; grows to 10s of GB
  "--exclude=dblp_parsed/"             # 433MB JSONL — regenerable from XML
  "--exclude=_ipeds_cache/"            # NCES zip cache — regenerable
  "--exclude=_ipeds_probe/"            # probe zips — regenerable
  "--exclude=__pycache__/"             # generated bytecode
  "--exclude=*.pyc"
  "--exclude=*.pyo"
  "--exclude=.ipynb_checkpoints/"
  "--exclude=.DS_Store"
  "--exclude=*.html"                   # intermediate HTML from md-to-pdf conversion
  "--exclude=dblp.xml"                  # multi-GB DBLP dump — never sync accidentally
  "--exclude=dblp.xml.gz"               # multi-GB DBLP dump — never sync accidentally
  "--exclude=dblp.xml.gz.md5"           # companion checksum — sync manually if needed
)

# Extra excludes for PUSH (Mac → HPC): don't overwrite HPC-generated large data
# from a Mac that may have stale or missing copies of those files.
_IVY_RSYNC_PUSH_EXCLUDES=(
  "--exclude=faculty_panel.jsonl"
  "--exclude=faculty_panel_collisions.jsonl"
  "--exclude=faculty_panel_enriched.jsonl"
  "--exclude=faculty_panel_with_pools.jsonl"
  "--exclude=faculty_panel_analysis*.jsonl"
  "--exclude=faculty_snapshots_plan.jsonl"
  "--exclude=faculty_snapshots_strategy_audit.jsonl"
  "--exclude=faculty_snapshots_index.jsonl"
  "--exclude=faculty_snapshots_parsed.jsonl"
  "--exclude=openalex_author_ids.jsonl"
  "--exclude=openalex_works_by_year.jsonl"
  "--exclude=openalex_snapshot_cache.jsonl"   # HPC-generated cache — never push from Mac
  "--exclude=openalex_low_confidence.jsonl"
  "--exclude=openalex_inst_map.json"
  "--exclude=faculty_url_suggestions.jsonl"   # HPC-generated by discover_faculty_urls.slurm
  "--exclude=faculty_url_suggestions.csv"     # same — pull only, never push
  "--exclude=faithful_537_sweep_results.jsonl" # local/HPC generated sweep stream — pull only
  "--exclude=faithful_537_sweep_stage*_results.csv"
  "--exclude=faithful_537_sweep_grouped_candidates.csv"
  "--exclude=faithful_537_sweep_README.md"
  "--exclude=candidate_plots/"
  "--exclude=rivanna_faithful_537/"            # HPC-generated sweep outputs — pull only
  "--exclude=faithful_538_sweep_results.jsonl"
  "--exclude=faithful_538_sweep_stage*_results.csv"
  "--exclude=faithful_538_sweep_grouped_candidates.csv"
  "--exclude=faithful_538_sweep_README.md"
  "--exclude=faithful_538_candidate_plots/"
  "--exclude=rivanna_faithful_538/"
)

_ivy_rsync_build_opts() {
  local ctrl_dir="${HOME}/.ssh/ivy-net-rsync"
  mkdir -p "${ctrl_dir}" "${HOME}/.ssh"
  # One SSH login per script run (subsequent rsync invocations reuse the socket).
  RSYNC_RSH="ssh -o ControlMaster=auto -o ControlPath=${ctrl_dir}/cm-%r@%h:%p -o ControlPersist=600"
  RSYNC_OPTS=(-avz --progress -e "${RSYNC_RSH}")
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    RSYNC_OPTS+=(-n)
    echo "==> DRY RUN (no files changed)"
  fi
}

# Usage: ivy_rsync_push <relative-path>   e.g. tenure/tenure_pipeline
#   Pushes code and small tracked files; skips HPC-generated large data outputs.
ivy_rsync_push() {
  local rel="${1:?relative path required}"
  _ivy_rsync_build_opts
  local src="${REPO_ROOT}/${rel}/"
  local dst="${REMOTE}:${HPC_REPO}/${rel}/"
  echo "==> Push (code + small files) ${rel}"
  echo "    from: ${src}"
  echo "    to:   ${dst}"
  rsync "${RSYNC_OPTS[@]}" \
    "${_IVY_RSYNC_COMMON_EXCLUDES[@]}" \
    "${_IVY_RSYNC_PUSH_EXCLUDES[@]}" \
    "${src}" "${dst}"
  echo "==> Done."
}

# Usage: ivy_rsync_pull <relative-path>
#   Pulls all generated outputs from HPC (enriched panels, OA files, PNGs, CSVs).
#   Skips faculty_snapshots/ and dblp_parsed/ (too large for Mac).
ivy_rsync_pull() {
  local rel="${1:?relative path required}"
  _ivy_rsync_build_opts
  local src="${REMOTE}:${HPC_REPO}/${rel}/"
  local dst="${REPO_ROOT}/${rel}/"
  echo "==> Pull (all outputs except HTML + dblp) ${rel}"
  echo "    from: ${src}"
  echo "    to:   ${dst}"
  mkdir -p "${dst}"
  rsync "${RSYNC_OPTS[@]}" \
    "${_IVY_RSYNC_COMMON_EXCLUDES[@]}" \
    "${src}" "${dst}"
  echo "==> Done."
}

# Usage: ivy_rsync_pull_sweep
#   Pulls generated faithful 537 + 538 sweep outputs only. It deliberately does not
#   pull sweep source code back from HPC, because rsync can overwrite local edits.
ivy_rsync_pull_sweep() {
  _ivy_rsync_build_opts
  local rel="${IVY_RSYNC_SWEEP_TARGET}"
  local src="${REMOTE}:${HPC_REPO}/${rel}/"
  local dst="${REPO_ROOT}/${rel}/"
  echo "==> Pull faithful 537 + 538 sweep results only"
  echo "    from: ${src}"
  echo "    to:   ${dst}"
  mkdir -p "${dst}"
  rsync "${RSYNC_OPTS[@]}" \
    "${_IVY_RSYNC_COMMON_EXCLUDES[@]}" \
    "--include=/rivanna_faithful_537/***" \
    "--include=/faithful_537_sweep_results.jsonl" \
    "--include=/faithful_537_sweep_stage*_results.csv" \
    "--include=/faithful_537_sweep_grouped_candidates.csv" \
    "--include=/faithful_537_sweep_README.md" \
    "--include=/candidate_plots/***" \
    "--include=/rivanna_faithful_538/***" \
    "--include=/faithful_538_sweep_results.jsonl" \
    "--include=/faithful_538_sweep_stage*_results.csv" \
    "--include=/faithful_538_sweep_grouped_candidates.csv" \
    "--include=/faithful_538_sweep_README.md" \
    "--include=/faithful_538_candidate_plots/***" \
    "--exclude=*" \
    "${src}" "${dst}"
  echo "==> Done."
}

# Unzip git-tracked Big Fish archives when unzipped CSVs are missing (Mac/local; no network).
ivy_unzip_big_fish() {
  local football_dir="${REPO_ROOT}/datasets/football"
  local football_csv="${football_dir}/football_big_fish_player_season_panel/football_big_fish_player_season_panel.csv"
  local football_zip="${football_dir}/football_big_fish_player_season_panel.csv.zip"
  local legends_dir="${REPO_ROOT}/datasets/legends"
  local legends_csv="${legends_dir}/lol_big_fish_player_split_panel.csv"
  local legends_zip="${legends_dir}/lol_big_fish_player_split_panel.csv.zip"

  if [[ -f "${football_csv}" ]]; then
    echo "==> OK (exists): datasets/football/.../football_big_fish_player_season_panel.csv"
  else
    if [[ ! -f "${football_zip}" ]]; then
      echo "ERROR: missing datasets/football/football_big_fish_player_season_panel.csv.zip — run git pull first." >&2
      exit 1
    fi
    mkdir -p "${football_dir}/football_big_fish_player_season_panel"
    echo "==> Unzip football panel (zip is flat csv → move into panel subdir)"
    unzip -o -q "${football_zip}" -d "${football_dir}"
    if [[ -f "${football_dir}/football_big_fish_player_season_panel.csv" ]]; then
      mv -f "${football_dir}/football_big_fish_player_season_panel.csv" "${football_csv}"
    fi
    rm -f "${football_dir}/__MACOSX" "${football_dir}/._football_big_fish_player_season_panel.csv" 2>/dev/null || true
    if [[ ! -f "${football_csv}" ]]; then
      echo "ERROR: football unzip did not produce ${football_csv}" >&2
      exit 1
    fi
  fi

  if [[ -f "${legends_csv}" ]]; then
    echo "==> OK (exists): datasets/legends/lol_big_fish_player_split_panel.csv"
  else
    if [[ ! -f "${legends_zip}" ]]; then
      echo "ERROR: missing datasets/legends/lol_big_fish_player_split_panel.csv.zip — run git pull first." >&2
      exit 1
    fi
    mkdir -p "${legends_dir}"
    echo "==> Unzip legends panel"
    unzip -o -q "${legends_zip}" -d "${legends_dir}"
    rm -rf "${legends_dir}/__MACOSX" 2>/dev/null || true
    if [[ ! -f "${legends_csv}" ]]; then
      echo "ERROR: legends unzip did not produce ${legends_csv}" >&2
      exit 1
    fi
  fi

  echo "==> Big Fish CSVs ready."
}

# Pull selected datasets/ subtrees: HPC → Mac (include-only; one rsync).
ivy_rsync_pull_big_data() {
  ivy_rsync_sync_big_data pull "${1:-datasets}"
}

# Back-compat alias
ivy_rsync_pull_big_fish() {
  ivy_rsync_sync_big_data pull big-fish
}

# Push selected datasets/ subtrees: Mac → HPC (include-only; one rsync).
ivy_rsync_push_big_data_scoped() {
  ivy_rsync_sync_big_data push "${1:-datasets}"
}

# Push gitignored Big Fish unzipped CSVs: Mac → HPC (single rsync / single SSH session).
ivy_rsync_push_big_fish() {
  ivy_rsync_sync_big_data push big-fish
}

# Push all datasets/ big trees in one rsync.
ivy_rsync_push_big_data() {
  ivy_rsync_sync_big_data push datasets
}

# Pull bulk men's basketball data tree (gitignored under datasets/mbb/).
ivy_rsync_pull_mbb() {
  ivy_rsync_pull "${IVY_RSYNC_MBB_TARGET}"
}

# Push bulk men's basketball data tree (Mac → HPC).
ivy_rsync_push_mbb() {
  ivy_rsync_push "${IVY_RSYNC_MBB_TARGET}"
}

# Usage: ivy_rsync_push_faithful_538_deps
#   Push Tier-1 generative modules (Mac → HPC). empirical_perf_fit.json is Git-tracked
#   at datasets/mbb/ — use git pull on Rivanna; rsync copy below is optional backup.
ivy_rsync_push_faithful_538_deps() {
  local fit="${REPO_ROOT}/datasets/mbb/empirical_perf_fit.json"
  if [[ ! -f "$fit" ]]; then
    echo "WARN: missing ${fit} — run 530 CELL 5b and commit, or git pull on HPC." >&2
  fi
  echo "==> Push faithful 538 model dependencies"
  ivy_rsync_push "sports/sports_pipeline"
  local files=(
    "sports/tier1_sim_config.py"
    "sports/tier1_pool_assignment.py"
    "sports/tier1_generative_eda.py"
    "datasets/mbb/empirical_perf_fit.json"
  )
  _ivy_rsync_build_opts
  for rel in "${files[@]}"; do
    local src="${REPO_ROOT}/${rel}"
    if [[ ! -f "$src" ]]; then
      echo "ERROR: missing ${src}" >&2
      exit 1
    fi
    local dst="${REMOTE}:${HPC_REPO}/${rel}"
    echo "    ${rel}"
    rsync "${RSYNC_OPTS[@]}" \
      "${_IVY_RSYNC_COMMON_EXCLUDES[@]}" \
      "${src}" "${dst}"
  done
  echo "==> Done."
}
